### ISSUE TITLE
Platform-specific conda environment files

### ISSUE THREAD

**Issue by thazhemadam** [aced-differentiate/AtomicGraphNets.jl#54]
Currently, the conda environment files provided for example 1 - [conda_env_specfile.txt](https://github.com/aced-differentiate/AtomicGraphNets.jl/blob/master/examples/1_formation_energy/conda_env_specfile.txt) and [pmg_environment.yml](https://github.com/aced-differentiate/AtomicGraphNets.jl/blob/master/examples/1_formation_energy/pmg_environment.yml) are both osx-64 specific.
This means that this environment cannot be recreated on systems running on a different configuration (say Linux, or Windows, or even a different architecture) for obvious reasons.
Trying to resolve the missing package errors by replacing the version with the closest thing available for Linux (and removing if there are no matching packages - like `appnope`), only results in more package version conflicts between dependencies.

Is there any solution to ensure that this example is actually executable, other than resorting to creating a platform-specific `environment.yml` from scratch for Linux and Windows?

P.S. - If the existing environment.yml file is due for a version bump, please keep in mind that the `from pymatgen import MPRester` [here](https://github.com/aced-differentiate/AtomicGraphNets.jl/blob/83b2b9f49c4716b2de4051b90ae9263776585929/examples/1_formation_energy/download_data.py#L1) will have to be updated to be `from pymatgen.ext.matproj import MPRester`, owing to a backwards incompatible change introduced in v2022.0.*.

**Comment by thazhemadam** [comment]
Seeing how the dependencies are primarily for `pymatgen`, I suggest we drop the environment spec files entirely, and instead mention in the documentation how to activate an environment, and install whichever pymatgen version,

**Comment by rkurchin** [comment]
Yeah, fixing that has been on my personal list for a bit and I just hadn't gotten to it yet – if you have the time and motivation to tackle it, what you describe sounds like a great solution!

**Comment by rkurchin** [comment]
if you do so and make a PR, be sure to note that it would resolve both this and #52
