### ISSUE TITLE
prepare for Flux v0.12

### ISSUE THREAD

**Issue by CarloLucibello** [aced-differentiate/AtomicGraphNets.jl#60]
Hi,
this is just a heads-up about the upcoming release of Flux v0.12:
although being a breaking release, the breakings are very mild and shouldn't affect most users. 
One thing to notice is that loss functions direct use from the Flux module, as in `Flux.mse`. have been deprecated for a couple of cycles now in favor of `Flux.Losses.mse` and will be removed in v0.12. Also, all loss functions perform by default mean aggregation, so no broadcasting is needed. Therefore, scripts like 
https://github.com/aced-differentiate/AtomicGraphNets.jl/blob/master/examples/1_formation_energy/formation_energy.j
should be fixed accordingly. 

Best,
Carlo

**Comment by rkurchin** [comment]
Thanks for the heads-up, Carlo! We'll be sure to fix those!
